version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: auction_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auction_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/auction_platform?replicaSet=rs0
      - JWT_SECRET=appzeto_super_secret_jwt_key_2026_production
      - JWT_EXPIRES_IN=7d
      - ANTI_SNIPING_THRESHOLD_SECONDS=120
      - ANTI_SNIPING_EXTENSION_SECONDS=120
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: auction_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
